<start>     ::= if_lower_else(Rem, c[<80,1000>], <exp0>, c[<0.5,1.5>])

<exp0>      ::= <factorSS> Rem^(<factorS>)             |
                (<factorS>)*Rem <factorSS>             |
                (<factorS>)*Rem^(<factorS>)
                

<factorSS>  ::= <fS><fS><fS><fS>
<factorS>   ::= ((<factor> + 0<fS>)     / (1<fS><fS>))              |
                ((<factor> + <factor>)  / (1<fS><fS>))              |
                ((<factor> + 0<fS>)     / (<factor> + <factor>))    |
                ((<factor> + <factor>)  / (<factor> + 0<fS>))       |
                ((<factor> + <factor>)  / (<factor> + <factor>))    

<fS>        ::= <f><f>
<factor>    ::= (<factor0>) <f> |
                (<factor1>) <f> | (<factor0>)*(<factor1>)   |
                (<factor2>) <f> | (<factor0>)*(<factor2>)   |
                (<factor3>) <f> | (<factor0>)*(<factor3>)   |
                (<factor4>) <f> | (<factor0>)*(<factor4>)   |
                (<factor5>) <f> | (<factor0>)*(<factor5>)       


<f>         ::= <&2><&2><&2><&2><&2>

<factor0>   ::= c[<-100,100>]<&1> <&2><&2><&2><&2>

<factor1>   ::= <An> <&2><&2><&2><&2>           |
                <Dfn> <&2><&2><&2><&2>          |
                <fluidColumn> <&2><&2><&2><&2>  |
                <S> <&2><&2><&2><&2>            |
                <colIndex> <&2><&2><&2><&2> 

<factor2>   ::= <An>*<Dfn> <&2><&2><&2>                 |
                <An>*<fluidColumn> <&2><&2><&2>         | 
                <An>*<S> <&2><&2><&2>                   | 
                <An>*<colIndex> <&2><&2><&2>            | 
                <Dfn>*<fluidColumn> <&2><&2><&2>        | 
                <Dfn>*<S> <&2><&2><&2>                  | 
                <Dfn>*<colIndex> <&2><&2><&2>           | 
                <fluidColumn>*<S> <&2><&2><&2>          | 
                <fluidColumn>*<colIndex> <&2><&2><&2>   | 
                <S>*<colIndex> <&2><&2><&2>                         

<factor3>   ::= <An>*<Dfn>*<fluidColumn> <&2><&2>       |
                <An>*<Dfn>*<S> <&2><&2>                 |
                <An>*<Dfn>*<colIndex> <&2><&2>          |
                <An>*<fluidColumn>*<S> <&2><&2>         |
                <An>*<fluidColumn>*<colIndex> <&2><&2>  |
                <An>*<S>*<colIndex> <&2><&2>            |
                <Dfn>*<fluidColumn>*<S> <&2><&2>        |
                <Dfn>*<fluidColumn>*<colIndex> <&2><&2> |
                <Dfn>*<S>*<colIndex> <&2><&2>           |
                <fluidColumn>*<S>*<colIndex> <&2><&2>   


<factor4>   ::= <An>*<Dfn>*<fluidColumn>*<S> <&2>           |
                <An>*<Dfn>*<fluidColumn>*<colIndex> <&2>    |
                <An>*<Dfn>*<S>*<colIndex> <&2>              |
                <An>*<fluidColumn>*<S>*<colIndex> <&2>      |
                <Dfn>*<fluidColumn>*<S>*<colIndex> <&2>     

<factor5>   ::= <An>*<Dfn>*<fluidColumn>*<S>*<colIndex>     




<&2>            ::= <&1>
<An>            ::= An <&1>             | An^c[<-10,10>]            |
<Dfn>           ::= Dfn <&1>            | Dfn^c[<-10,10>]           |
<fluidColumn>   ::= fluidColumn <&1>    | fluidColumn^c[<-10,10>]   |
<S>             ::= S <&1>              | S^c[<-10,10>]             |
<colIndex>      ::= colIndex <&1>       | colIndex^c[<-10,10>]



<&1>        ::= &
<-2,2>      ::= GE_constants:-2_0.01_2
<-10,10>    ::= GE_constants:-10_0.1_10
<-100,100>  ::= GE_constants:-100_0.1_100
<0,2>       ::= GE_constants:0_0.1_2
<0.5,1.5>   ::= GE_constants:0.5_0.01_1.5
<0,3>       ::= GE_constants:0_0.1_3
<80,1000>   ::= GE_constants:80_1_1000
<800,1000>  ::= GE_constants:800_1_1000
<-3,-1>     ::= GE_constants:-3_0.1_-1