<start> ::= <expr1>
<expr1> ::= ((<expr2>)<op>(<expr2>)) | (<expr2>)
<expr2> ::= ((<expr3>)<op>(<expr3>)) | (<expr3>)
<expr3> ::= ((<expr4>)<op>(<expr4>)) | (<expr4>)
<expr4> ::= ((<var>)<op>(<var>)) | (<var>)
<op> ::=  + | - | * | ** | / 
<var> ::= S|An|Rem|Dfn|colIndex | c[<num>]
<num> ::= <-1,1>|<-10,10>|<-100,100>|<-1000,1000>

<-1,1>      ::= GE_constants:-1_0.001_1
<-10,10>    ::= GE_constants:-10_0.001_10
<-100,100>  ::= GE_constants:-100_0.01_100
<-1000,1000>  ::= GE_constants:-1000_1_1000